server:
  port: 3344


spring:
  datasource:
    username: root
    password: huiya123
    url: jdbc:mysql://localhost:3306/cloudDB01        # 数据库名称
  application:
    name:  microservicecloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/BlueBlueskyMuc/microservicecloud-config.git #GitHub上面的git仓库名字


